### PR TITLE
Update community supported README: legal disclaimer

### PR DESCRIPTION
**Pull request by cwarnermm**
Added legal disclaimer to README, as requested by Product.

### CODE REVIEW

**Review by fmartingr — APPROVED** [review]
Thank you Carrie!

**Comment by hanzei** [comment]
@fmartingr I'm confused. We use this plugin on Community. Are there customers who use it?

**Comment by cwarnermm** [comment]
@hanzei - @jasonblais asked for the disclaimer to be added to this repository. He may be a better person to answer your question.

**Comment by jasonblais** [comment]
@hanzei we have plenty of plugins used on community.mattermost.com that have this same disclaimer.

Mattermost will continue to actively maintain a select number of plugins, including Jira, GitHub, GitLab, MS Teams Sync, Calls, ServiceNow, and Zoom.

https://forum.mattermost.com/t/upcoming-product-changes-to-boards-and-various-plugins/16669

Let me know if this context helps?

**Pull request merged**
