### PR TITLE
Added point about enabling Google Calendar API, corrected link for co…

### PR DESCRIPTION
**Pull request by jedziemyjedziemy**
…mplete

### CODE REVIEW

**Comment by mickmister** [comment]
The misconfiguration of the plugin that this PR tries to avoid was causing a panic in the plugin. See the conversation here https://community-daily.mattermost.com/core/pl/j1xkbhxkf7d65nip5z9feoe39e . The panic still needs to be addressed.

```
2020-04-22T13:42:19.556+0200    debug   plugin/hclog_adapter.go:35      panic: runtime error: index out of range        {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35              {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35      goroutine 35 [running]: {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35      main.(*Plugin).completeCalendar(0xc0000a8f50, 0xcd32c0, 0xc000021830, 0xc0001de300)     {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35              /home/f/git/mattermost-plugin-google-calendar-abdul/server/api.go:83 +0x8ab     {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35      github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).ServeHTTP(0xc00000e600, 0xc00000f520, 0x11ffcc8, 0x0, 0x0)     {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35              /home/f/go/pkg/mod/github.com/mattermost/mattermost-server@v1.4.1-0.20191016162522-6597fdb40134/plugin/client_rpc.go:358 +0x293 {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35      reflect.Value.call(0xc000266180, 0xc00009a8f0, 0x13, 0xbbf995, 0x4, 0xc000053f18, 0x3, 0x3, 0xc000064400, 0xc0001e2aa8, ...)    {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35              /usr/lib/go-1.12/src/reflect/value.go:447 +0x461        {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35      reflect.Value.Call(0xc000266180, 0xc00009a8f0, 0x13, 0xc00022cf18, 0x3, 0x3, 0xc0001e2a80, 0xc00022cf10, 0xc00022cfb8)  {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35              /usr/lib/go-1.12/src/reflect/value.go:308 +0xa4 {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35      net/rpc.(*service).call(0xc0001c3b40, 0xc0000a9130, 0xc000097948, 0xc000097970, 0xc000102d80, 0xc00008dde0, 0xa70ea0, 0xc00000f520, 0x16, 0xa815a0, ...)        {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35              /usr/lib/go-1.12/src/net/rpc/server.go:384 +0x14e       {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35      created by net/rpc.(*Server).ServeCodec {"plugin_id": "calendar"}
2020-04-22T13:42:19.557+0200    debug   plugin/hclog_adapter.go:35              /usr/lib/go-1.12/src/net/rpc/server.go:481 +0x42b       {"plugin_id": "calendar"}
2020-04-22T13:42:19.564+0200    error   mlog/log.go:174 Plugin failed to ServeHTTP, RPC call failed     {"plugin_id": "calendar", "error": "unexpected EOF"}
```

Index out of range error here
https://github.com/mattermost/mattermost-plugin-google-calendar/blob/f85d05be8bdfdb8d7a9b52353a19a6a42f9f1b91/server/api.go#L83

**Comment by mickmister** [comment]
Ticket made here https://github.com/mattermost/mattermost-plugin-google-calendar/issues/8

@jfrerich Mentioning you for visibility

**Comment by hanzei** [comment]
@jedziemyjedziemy Would you be open on signing the CLA?

**Comment by jasonblais** [comment]
@jedziemyjedziemy unfortunately we're unable to accept the contribution without you signing the CLA ([contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)). As a result, we'll have to close your pull request for now.

If you have any questions about the CLA, would be happy to answer them. Thanks again for your help identifying the gap in our documentation and proposing an update to it.

**Comment by jasonblais** [comment]
cc @jfrerich @mickmister

**Pull request closed without merging**
