### PR TITLE
HA compatible

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Make HA Compatible

### CODE REVIEW

**Comment by hahmadia** [comment]
Not sure why the cron job is not posting the message every minute like I expect it too :( Only does the first time but never after that.

**Comment by mickmister** [comment]
Nice work! From your post:

> There was only one cron job running every minute. I tried migrating it to use the above cluster API. Problem is that it works on startup but never works after that.
>
> So when I connect my calendar, it will post the message `Test Job123123` but then every minute after it doesn't post the message anymore.

I'm not sure about why the job is only running once. Do you have any ideas about what code is not running in the imported `mattermost-plugin-api` code?

Instead of running a separate job for each user, I suggest running just one job that will service all users. This will require the plugin to save info about each user in one array in the kv store. Then in the one job, iterate over that array and process each 
user separately.

**Review by mickmister — CHANGES_REQUESTED** [review]
Request for single job

**Comment by mickmister** [comment]
Check out the job implementation here https://github.com/mattermost/mattermost-plugin-mscalendar/blob/e05112bcad3ad6129b9fe2886a4f3a8056120ea2/server/mscalendar/availability.go#L41

**Comment by hahmadia** [comment]
@mickmister Done! I implemented a simpler version. As for the jobs not running properly, I think it was something locally. After a restart and nuke, the jobs are running as expected.

**Comment by hahmadia** [comment]
^^ Also added https://github.com/mattermost/mattermost-plugin-google-calendar/issues/28

**Review by mickmister — CHANGES_REQUESTED** [review]
Awesome work :+1: I have one request for how we're storing the aggregate user data, and handling race conditions on saving the array.

I'd like to have a deeper discussion on how the plugin is saving events, and what logic it uses to be aware of upcoming events.

**Pull request closed without merging**
