### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by fmartingr**
#### Summary
- Updated project scaffolding to match latest changes.
- Migrate from `mattermost-server/v6` to `public`/`model` packages.
- Update to latest Google Calendar API (closes #69)
- Version bump.

### CODE REVIEW

**Comment by esarafianou** [comment]
@fmartingr can we get 2 dev reviews before the security one?

**Review by hanzei — APPROVED** [review]
LGTM.

There are some recent changes in https://github.com/mattermost/mattermost-plugin-starter-template that I would like to see in here (like the logs command), but that is not a blocker.

**Review by mickmister — APPROVED** [review]
LGTM :tada:

**Comment by fmartingr** [comment]
> LGTM.
> 
> There are some recent changes in https://github.com/mattermost/mattermost-plugin-starter-template that I would like to see in here (like the logs command), but that is not a blocker.

Can you open an issue with the missing changes so I can keep track of it? I already updated some stuff from mscalendar. Maybe we can create a command to update common files automatically?

**Comment by hanzei** [comment]
Sure, created https://github.com/mattermost/mattermost-plugin-google-calendar/issues/71

**Comment by fmartingr** [comment]
@esarafianou Dev reviews are done.

**Review by esarafianou — APPROVED** [review]
LGTM 🚢

**Pull request merged**
