### PR TITLE
[GH-22] Add autocomplete icon

### LINKED ISSUE #22: Add autocomplete icon
Since v5.24 slash commands can provide an `svg` via  `AutocompleteIconData` in `model.Command` that is then shown in the autocomplete list. This ticket is about adding the icon in `assets` to the slash command.

Include screenhots from a dark and a bright theme in the PR description, as there might be the need for a separate icon with a white background for autocomplete.

Similar PRs:
For GitHub plugin https://github.com/mattermost/mattermost-plugin-github/pull/359
For Jira plugin https://github.com/mattermost/mattermost-plugin-jira/pull/653

### PR DESCRIPTION
**Pull request by ByeongsuPark**
#### Summary
Screenshot_2020-10-25_10-58-05
Screenshot_2020-10-25_10-58-41
Add autocomplete icon

#### Ticket Link

Fixes #22

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Amazing :rocket:

**Review by hahmadia — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann This might be another good dev testing ticket

**Review by hanzei — APPROVED** [review]
Tested on dark and bright theme. Looks good on both. No regressions found.

**Comment by hanzei** [comment]
Thanks for another great contribution @ByeongsuPark :+1:

**Pull request merged**
